config/routes.rb
Rails.application.routes.draw do


  get 'doctor/index'

  get 'users/new'

  get 'user/new'

  get 'welcome/index'

  #post '/doctors', to: 'doctors#save', as: 'save_doctor'

  get '/blogs', to: 'blogs#index', as: 'blogs' 
  get '/blogs/new', to: 'blogs#new', as: 'new_blog'   
  get '/blogs/:id', to: 'blogs#show', as: 'blog'  
  post '/blogs', to: 'blogs#create', as: 'create_blog'  
  get '/blogs/:id/edit', to: 'blogs#edit', as: 'edit_blog'  
  patch '/blogs/:id', to: 'blogs#update', as: 'update_blog'  
  delete '/blogs/:id', to: 'blogs#destroy', as: 'delete_blog'  




  resources :doctors, only: [:index, :create, :update]

    resources :users do
    resources :roles
   end 

   resources :users do
   resources :live_classes
   end 



  resources :students

  resources :doctors do
  resources :patients
  end
  # get '/users/:user_id/live_classes/new', to: 'live_classes#new', as: 'new_live_class'
  # post '/users/:user_id/live_classes', to: 'live_classes#create', as: 'create_live_class'
  # get '/users/:user_id/live_classes/:id', to: 'live_classes#show', as: 'live_class'




  get 'docrors/index'

  get  '/users/:id' , to: 'users#show' , as: 'show_users'

  delete 'delet_students', to: 'students#delete_students' , as: :delete_students
  delete 'delete_users', to: 'users#delete_users', as: :delete_users
    
   root 'blogs#index' 


  end

















#def index
 #    @patients = Patient.all.map{ |p| [p.name, p.id] }
  #  if params[:patient_id].present?
  #    @patient = Patient.find(params[:patient_id])
  #    @doctors = @patient.doctors
  #  else
  #    @patient = nil
   #   @doctors = Doctor.all
   # end








   # <% if !@doctor.new_record? %>
   # <%= hidden_field_tag :id, @doctor.id %>
  # <% end %>

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :students, through: :student_projects
	has_many :student_projects
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :projects , through: :student_projects
	has_many :student_projects, dependent: :destroy

	has_many :blogs
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.all
    if params[:student].present? and params[:student][:project_id].present?
      @project= Project.find_by_id(params[:student][:project_id])
      @students = Student.eager_load(student_projects: :project).where("projects.pname =?", @project.pname)
      @details = []
      @students.each do|student|
        @name= student.name 
        @email = student.email
        @contact_no = student.contact_no
        @projects = student.student_projects
        @student_project_details = []
        @projects.each do|student_project|
          @student_project_details << student_project.project.pname
        end
        @details << {:name=>@name, :email=>@email, :contact_no=>@contact_no, :student_project_details=> @student_project_details,:student=>student}
      end  
    end
  end

  def show 
  end

  def new
    @student = Student.new

  end

  def edit
  end
 
  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end


  def update
    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  def delete_students
    Student.where(id: params[:student_ids]).destroy_all
    redirect_to students_path, notice: "student deleted successfully"
  end


  private
  def set_student
    @student= Student.find(params[:id])
  end


  private
  def student_params
    params.require(:student).permit(:name, :email, :contact_no )
  end



 
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student do |f| %>

  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email%><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :contact_no%><br>
    <%= f.text_field :contact_no %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/edit.html.erb
<h1>Edit students</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
	<%= link_to 'New student', new_student_path  %>



<style>
  table {
    border-collapse: collapse;
  }
  td, th {
    border: 1px solid black;
  }
  td + td, th + th {
    border-left: none;
  }
</style>
<% if @details.present? %>
<h1>list of students<h1>
<%= form_tag delete_students_path, method: :delete do %>

<table style="border-spacing: 10px;">
<tr>
<th>select</th>
<th>name</th>
<th>email</th>
<th>contact_no</th>
<th>project_name</th>
<th colspan="3"><th>
</tr>
<% @details.each do |details| %>
<tr>
<td><%= check_box_tag "student_ids[]", details[:student].id %></td>
<td><%= details[:name] %> </td>
<td><%= details[:email] %> </td>
<td><%= details[:contact_no] %> </td>
<td><%= details[:student_project_details].join(",") %> </td>
<td><%= link_to 'Show', student_path(details[:student]) %></td>
<td><%= link_to 'Edit', edit_student_path(details[:student]) %></td>
 <td><%= link_to 'Destroy', student_path(details[:student]),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
<% end %>
</tr>
</table>
<%= submit_tag "Delete selected students" %>
<% end %>
<% end %>


<%= form_tag(students_path, method: :get) do %>
 <%= select_tag 'student[project_id]', options_from_collection_for_select(Project.all, :id, :pname) %>
<%= submit_tag "Submit" %>
<% end %> 

app/views/students/new.html.erb
<h1>New student</h1>
 
<%= render 'form' %>
 

app/views/students/show.html.erb
<p>
  <strong>name:</strong>
  <%= @student.name%>
</p>
 
<p>
  <strong>email:</strong>
  <%= @student.email%>
</p>

<p>
  <strong>contact_no:</strong>
  <%= @student.contact_no %>
</p>
 
  
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

 