config/routes.rb
Rails.application.routes.draw do


  get 'doctor/index'

  get 'users/new'

  get 'user/new'

  get 'welcome/index'

  #post '/doctors', to: 'doctors#save', as: 'save_doctor'

  get '/blogs', to: 'blogs#index', as: 'blogs' 
  get '/blogs/new', to: 'blogs#new', as: 'new_blog'   
  get '/blogs/:id', to: 'blogs#show', as: 'blog'  
  post '/blogs', to: 'blogs#create', as: 'create_blog'  
  get '/blogs/:id/edit', to: 'blogs#edit', as: 'edit_blog'  
  patch '/blogs/:id', to: 'blogs#update', as: 'update_blog'  
  delete '/blogs/:id', to: 'blogs#destroy', as: 'delete_blog'  




  resources :doctors, only: [:index, :create, :update]

    resources :users do
    resources :roles
   end 

   resources :users do
   resources :live_classes
   end 



  resources :students

  resources :doctors do
  resources :patients
  end
  # get '/users/:user_id/live_classes/new', to: 'live_classes#new', as: 'new_live_class'
  # post '/users/:user_id/live_classes', to: 'live_classes#create', as: 'create_live_class'
  # get '/users/:user_id/live_classes/:id', to: 'live_classes#show', as: 'live_class'




  get 'docrors/index'

  get  '/users/:id' , to: 'users#show' , as: 'show_users'

  delete 'delet_students', to: 'students#delete_students' , as: :delete_students
  delete 'delete_users', to: 'users#delete_users', as: :delete_users
    
   root 'blogs#index' 


  end

















#def index
 #    @patients = Patient.all.map{ |p| [p.name, p.id] }
  #  if params[:patient_id].present?
  #    @patient = Patient.find(params[:patient_id])
  #    @doctors = @patient.doctors
  #  else
  #    @patient = nil
   #   @doctors = Doctor.all
   # end








   # <% if !@doctor.new_record? %>
   # <%= hidden_field_tag :id, @doctor.id %>
  # <% end %>

app/models/role.rb
class Role < ActiveRecord::Base
   has_many :users, :through => :user_roles
   has_many :user_roles
end

app/models/user.rb
class User < ActiveRecord::Base
    
      #giving association
      has_many :roles, :through => :user_roles
      has_many :user_roles, dependent: :destroy

      has_many :live_classes

      attr_accessor :contact_no_temporary
      
      #adding validation
      validates :name, presence: true,  format: { without: /\d/} 
      validates :contact_no, presence: true, length: { is: 10 }
      validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: {case_sensitive: false}
      validates :gender, presence: true, inclusion: { in: %w(male female other ) } ,on: :gender_validation

      before_save :update_user_name
      before_validation :format_contact_no
      before_validation :set_default_gender
      after_update :show_message
      after_destroy :log_destroy_action


      # def self.search(search)
      #       where("name LIKE ?", "%#{search}%")
      #       where("email LIKE ?", "%#{search}%")
      #       where("contact_no LIKE ?", "%#{search}%")
      # end

      
      private
      def set_default_gender
            self.gender = "other" if gender.blank?
      end

	
      private
      after_find do |user|
            puts "You have found an object!"
      end

      private
      def update_user_name
            self.name.downcase!
      end

      private
      def format_contact_no
            self.contact_no = contact_no.gsub(/\D/, '')
      end

      private
      def show_message
            puts "===========user is updated==============="
      end


      def log_destroy_action
            puts '=====user destroyed========'
      end
      
      def self.search(search)
            where('name LIKE :query OR email LIKE :query OR contact_no LIKE :query', { query: "%#{search}%" })
      end












                   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  helper_method :formated_date

  def index
    if params[:search]
        @userss = User.search(params[:search])
      else
        @userss = User.all
      end

    @roles = Role.all
    if params[:user].present? and params[:user][:role_id].present?
      @role= Role.find_by_id(params[:user][:role_id])
      puts "==#{@role}=="
      @users = User.eager_load(user_roles: :role).where("roles.role =?", @role.role)
      "====#{@users}==="
      @details = []
      @users.each do|user|
        @name= user.name 
        @email = user.email
        @contact_no = user.contact_no
        @gender = user.gender
        @country = user.country
        @roles=user.user_roles
        @user_role_details = []
        @roles.each do|user_role|
          @user_role_details << user_role.role.role
        end
        @details << {:name=>@name, :email=>@email, :contact_no=>@contact_no,:gender=>@gender, :country=>@country, :user_roles_detailes=>@user_role_details,:user=>user}
      end  
    end
  end

  def show 
   @user = User.find(params[:id]) 
   @live_class = @user.live_classes.build
  end

  def new
    @user = User.new
     

  end

  def edit

  end
 
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end


  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def delete_users
    User.where(id: params[:user_ids]).destroy_all
    redirect_to users_path, notice: "Users deleted successfully"
  end


  private
  def set_user
    @user= User.find(params[:id])
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :contact_no, :gender, :country, :role_id,:date_of_birth  )
  end

 def formated_date(date)
            date.strftime('%B %d, %Y at %I:%M %p')  if @user.date_of_birth.present?
      end

 
end


 

app/helpers/user_helper.rb
module UserHelper
  # def format_name(user)
  #   if user.gender == "male"
  #     "Mr. #{user.name}"
  #   elsif user.gender == "female"
  #     "Ms. #{user.name}"
  # else
  #   user.name
  #   end
  # end


  # def formated_date(date)
  #           date.strftime('%B %d, %Y at %I:%M %p')  if @user.date_of_birth.present?
  #     end


end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email%><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :contact_no%><br>
    <%= f.text_field :contact_no %>
  </p>

  <p>
    <%= f.label :gender%><br>
    <%= f.text_field :gender %>
  </p>

  <p>
    <%= f.label :country%><br>
    <%= f.text_field :country %>
    <P>

    <p>
    <%= f.label :dob%><br>
    <%= f.datetime_local_field  :date_of_birth%><br>
    <P>

   





  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
 
<%= render 'form' %> 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= link_to 'New user', new_user_path  %>
<style>
  table {
    border-collapse: collapse;
  }
  td, th {
    border: 1px solid black;
  }
  td + td, th + th {
    border-left: none;
  }
</style>
<% if @details.present? %>
<h1>list of users<h1>
<%= form_tag delete_users_path, method: :delete do %>
<table style="border-spacing: 10px;">
<tr>
<th>select</th>
<th>name</th>
<th>email</th>
<th>contact_no</th>
<th>gender</th>
<th>country</th>
<th>role_name</th>
<th colspan="3"><th>
</tr>
<% @details.each do |details| %>
<tr>
<td><%= check_box_tag "user_ids[]", details[:user].id %></td>
<td><%= details[:name] %> </td>
<td><%= details[:email] %> </td>
<td><%= details[:contact_no] %> </td>
<td><%= details[:gender] %> </td>
<td><%= details[:country] %> </td>
<td><%= details[:user_roles_detailes].join(",") %> </td>
<td><%= link_to 'Show', user_path(details[:user]) %></td>
<td><%= link_to 'Edit', edit_user_path(details[:user]) %></td>
 <td><%= link_to 'Destroy', user_path(details[:user]),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
<% end %>
</tr>
</table>
<%= submit_tag "Delete selected users" %>
<% end %>
<% end %>

<%= form_tag(users_path, method: :get) do %>
 <%= select_tag 'user[role_id]', options_from_collection_for_select(Role.all, :id, :role) %>
<%= submit_tag "Submit" %>
<% end %> 

<h2>search  doctors</h2>
<%= form_tag(users_path, method: :get) do %>
<p><%= text_field_tag(:search, params[:search]) %>
<%= submit_tag ("search") %></p>
<% end %>

<% if params[:search].present? %>
<% if @userss.present? %>
<h1>list of users<h1>
<%= form_tag delete_users_path, method: :delete do %>
<table style="border-spacing: 10px;">
<tr>
<th>select</th>
<th>name</th>
<th>email</th>
<th>contact_no</th>
<th>gender</th>
<th>country</th>
<th>role_name</th>
<th colspan="3"><th>
</tr>
<% @userss.each do |user| %>
<tr>
<td><%= check_box_tag "user_ids[]", user.id %></td>
<td><%=user.name  %> </td>
<td><%= user.email %> </td>
<td><%= user.contact_no %> </td>
<td><%= user.gender %> </td>
<td><%= user.country %> </td>
<td>
<ul>
<% user.roles.each do|role| %>
<li><%= role.role %></li>
<% end %>
</ul>
</td>
<td><%= link_to 'Show', user_path(user) %></td>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
 <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
<% end %>
<% end %>
<% end %>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>
 
<%= render partial: "form" %>

app/views/users/show.html.erb
<% if logged_in? %>Welcome, <%= current_user.name %><% end %>

<p>

  <strong>name:</strong>
  <%= format_name(@user)%>
</p>
 
<p>
  <strong>email:</strong>
  <%= @user.email%>
</p>

<p>
  <strong>contact_no:</strong>
  <%= @user.contact_no %>
</p>
 
<p>
  <strong>gender:</strong>
  <%= @user.gender %>
</p>
 
 <p>
  <strong>country:</strong>
  <%= @user.country %>
</p>
<p>
  <strong>date of birth:</strong>
  <%= formated_date(@user.date_of_birth) %>
</p>

<p><h2>roles:</h2></strong>
  <%= render partial: 'roles/role' , collection: @user.roles %>
</p>

<p><h2>class detailes</h2>
<%= render partial: 'live_classes/live_class', collection: @user.live_classes %>
</p>

<p><h3>Add a role:</h3>
<%= render 'roles/form' %>
</p>

<p><h3> create class: <h3>
<%= render 'live_classes/class_form' %>
</p>
  
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

 