config/routes.rb
Rails.application.routes.draw do


  get 'doctor/index'

  get 'users/new'

  get 'user/new'

  get 'welcome/index'

  #post '/doctors', to: 'doctors#save', as: 'save_doctor'

  get '/blogs', to: 'blogs#index', as: 'blogs' 
  get '/blogs/new', to: 'blogs#new', as: 'new_blog'   
  get '/blogs/:id', to: 'blogs#show', as: 'blog'  
  post '/blogs', to: 'blogs#create', as: 'create_blog'  
  get '/blogs/:id/edit', to: 'blogs#edit', as: 'edit_blog'  
  patch '/blogs/:id', to: 'blogs#update', as: 'update_blog'  
  delete '/blogs/:id', to: 'blogs#destroy', as: 'delete_blog'  




  resources :doctors, only: [:index, :create, :update]

    resources :users do
    resources :roles
   end 

   resources :users do
   resources :live_classes
   end 



  resources :students

  resources :doctors do
  resources :patients
  end
  # get '/users/:user_id/live_classes/new', to: 'live_classes#new', as: 'new_live_class'
  # post '/users/:user_id/live_classes', to: 'live_classes#create', as: 'create_live_class'
  # get '/users/:user_id/live_classes/:id', to: 'live_classes#show', as: 'live_class'




  get 'docrors/index'

  get  '/users/:id' , to: 'users#show' , as: 'show_users'

  delete 'delet_students', to: 'students#delete_students' , as: :delete_students
  delete 'delete_users', to: 'users#delete_users', as: :delete_users
    
   root 'blogs#index' 


  end

















#def index
 #    @patients = Patient.all.map{ |p| [p.name, p.id] }
  #  if params[:patient_id].present?
  #    @patient = Patient.find(params[:patient_id])
  #    @doctors = @patient.doctors
  #  else
  #    @patient = nil
   #   @doctors = Doctor.all
   # end








   # <% if !@doctor.new_record? %>
   # <%= hidden_field_tag :id, @doctor.id %>
  # <% end %>

app/models/doctor.rb
class Doctor < ActiveRecord::Base
    
     has_many :doctor_patients, dependent: :destroy
     has_many :patients, :through => :doctor_patients
       
      # validates :name, presence: true,  format: { without: /\d/} 
      # validates :contact_no, presence: true, length: { is: 10 }, :unless => :validate_contact_no?
      validates :email, presence: true
      validates :gender, presence: true, inclusion: { in: %w(male female other ) } ,on: :gender_validation

       
  #     attr_accessor :skip_contact_no_validation, :skip_email

  #     # before_destroy :delete_roles
  #     # before_save :validate_email
  #     # before_validation :ensure_name_has_a_value


  #    private
  #    def validate_contact_no?
  #       skip_contact_no_validation = true
  #    end

  #    #private
  #    #def validate_email?
  #    #    skip_email = true
  #   # end

  # private

  # def ensure_name_has_a_value
  #   if name.nil?
  #     self.name = "name"
  #   end
  # end

  # def delete_roles
  #   # Delete all the appointments associated with this doctor before deleting the doctor
  #   Role.where(user_id: id).destroy_all
  # end

   #def validate_email
    # Validate email address before saving the model
    #unless email =~ URI::MailTo::EMAIL_REGEXP
     # errors.add(:email, "is not a valid email address")
     # throw(:abort)
  # end

#   def self.search(doctor_name)
#     if doctor_name
#         doctor_name.downcase!
#         where('LOWER(name) LIKE ?', "%#{doctor_name}%")
#     else
#         all
#     end
# end

def self.search(search)
  where('name LIKE :query OR email LIKE :query OR contact_no LIKE :query', { query: "%#{search}%" }) 
end


     



end

# in form partial
# <p><strong>patients:</strong></p>
# <ul>
# <%= render partial: 'patients/patient', collection: @doctor.patients %>
# </ul>

#   <%= render 'patients/form' %>


# <%= form_tag(doctors_path, method: :get) do %>
# <p><%= text_field_tag(:search, params[:search]) %>
# <%= submit_tag ("search") %></p>
# <% end %>

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
     @doctorss = Doctor.all
    if params[:search]
      @doctors = Doctor.search(params[:search])
    else
      @doctors = Doctor.all
    end
    
    #@patients = Patient.all.map{ |p| [p.name, p.id] }
  
    #if params[:patient_id].present?
    #@patient = Patient.find(params[:patient_id])
    #@doctors = @patient.doctors
    #else
    #@patient = nil
    #@doctors = Doctor.all
    #end
  end

  def show
    @doctor = Doctor.find(params[:id])
    @patients = @doctor.patients
  end
 

  def new
    @doctor = Doctor.new
    @patients = Patient.all
    #@doctor_patient = @doctor.doctor_patients.build
  end

  def create
     @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
    # @doctor = Doctor.new(doctor_params)
    # patient = Patient.find_by(id: @doctor.id)

    # if patient.present?
    #   @doctor.patients << patient
    # end
   
 
    # if @doctor.save()
    #   redirect_to @doctor
    # else
    #   render 'new'
    # end 
  end

  def edit
     @doctor= Doctor.find(params[:id])
     @patients = Patient.all
  end

  def update
    @doctor= Doctor.find(params[:id])
    if @doctor.update(doctor_params)
      redirect_to @doctor
    else
      render 'edit'
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path 
  end

  def save
    @doctor = Doctor.new(doctor_params)
    if @doctor.save()
    redirect_to @doctor
    else
    render 'new'
    end 
  end
 
  private
  def doctor_params
    params.require(:doctor).permit(:name, :email, :contact_no, :doctor, :gender, :search,patient_ids: [] )
  end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>

  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@doctor.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @doctor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email%><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :contact_no%><br>
    <%= f.text_field :contact_no %>
  </p>
   <p>
    <%= f.label :gender%><br>
    <%= f.text_field :gender %>
  </p>

  <p>
<%= f.label :patient_ids, "Select Patients" %>
    <%= f.select :patient_ids, options_for_select(@patients.map{ |p| [p.name, p.id] }), {}, {multiple: true} %>

 </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/doctors/_form_tag.html.erb
  
  <%= form_tag(save_doctor_path, method: "post") do %>

    
   <div>
    <%= label_tag :name %> <br>
    <%= text_field_tag :'doctor[name]' %>
   </div>

   <div>
   <%= label_tag :email%><br>
    <%= text_field_tag :'doctor[email]' %>   
   </div>

   <div>
   <%= label_tag :contact_no%><br>
    <%= text_field_tag :'doctor[contact_no]' %>
   </div>

   <p>
   <%= submit_tag ("Create Doctor") %>
   </p>
   
<% end %>

app/views/doctors/_header.html.erb
<p>
  <strong>name:</strong>
  <%= doctor.name %>
</p>
 
<p>
  <strong>email:</strong>
  <%= doctor.email %>
</p>

<p>
  <strong>contact_no:</strong>
  <%= doctor.contact_no %>
</p>
<p>
  <strong>gender:</strong>
  <%= format_name(doctor.gender) %>
</p>

app/views/doctors/_new.html.erb
<%= form_tag(@doctor.new_record? ? doctors_path : doctor_path(@doctor), method: @doctor.new_record? ? "post" : "put") do %>

  <div>
    <%= label_tag :name %> <br>
    <%= text_field_tag :'doctor[name]', @doctor.name %>
  </div>

  <div>
    <%= label_tag :email%><br>
    <%= text_field_tag :'doctor[email]', @doctor.email %>
  </div>

  <div>
    <%= label_tag :contact_no%><br>
    <%= text_field_tag :'doctor[contact_no]', @doctor.contact_no %>
  </div>

  <p>
    <%= submit_tag @doctor.new_record? ? "Create Doctor" : "Update Doctor" %>
  </p>

<% end %>

app/views/doctors/edit.html.erb
<h1>Edit doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<%= link_to 'New doctor', new_doctor_path  %>

<style>
  table {
    border-collapse: collapse;
  }
  td, th {
    border: 1px solid black;
  }
  td + td, th + th {
    border-left: none;
  }
</style>


<h1>Listing doctors</h1>
<table>
<tr>
<th>name</th>
<th>email</th>
<th>contact_no</th>
<th>patient_name</th>
<th colspan="3"> </th>
</tr>
 
<% @doctorss.each do |doctor| %>
<tr>
<td><%= doctor.name %></td>
<td><%= doctor.email %></td>
<td><%= doctor.contact_no %></td>
<td>
  <ul>
<% doctor.patients.each do |patient| %>
<li> <%= patient.name %></li>
<% end %>
</ul>
</td>
<td><%= link_to 'Show', doctor_path(doctor) %></td>
<td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
<td><%= link_to 'destroy', doctor_path(doctor),
method: :delete, 
data:{confirm: 'are you sure?'}%></td>
</tr>
<% end %>
</table>

<h2>search  doctors</h2>

<%= form_tag(doctors_path, method: :get) do %>
<p><%= text_field_tag(:search, params[:search]) %>
<%= submit_tag ("search") %></p>
<% end %>


<% if params[:search].present? %>
  <% if @doctors.present? %>
<table>
<tr>
<th>name</th>
<th>email</th>
<th>contact_no</th>
<th>patient_name</th>
<th colspan="3"> </th>
</tr>
 
<% @doctors.each do |doctor| %>
<tr>
<td><%= doctor.name %></td>
<td><%= doctor.email %></td>
<td><%= doctor.contact_no %></td>
<td>
  <ul>
<% doctor.patients.each do |patient| %>
<li> <%= patient.name %></li>
<% end %>
</ul>
</td>
<td><%= link_to 'Show', doctor_path(doctor) %></td>
<td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
<td><%= link_to 'destroy', doctor_path(doctor),
method: :delete, 
data:{confirm: 'are you sure?'}%></td>
</tr>
<% end %>
</table>
    <% end %>
    <% end %>
     

    








  

app/views/doctors/new.html.erb
<h1>Create new doctor </h1>

 <%= render 'form' %>


 

app/views/doctors/show.html.erb
<p>
  <strong>name:</strong>
  <%= format_name(@doctor) %>
</p>
 
<p>
  <strong>email:</strong>
  <%= @doctor.email %>
</p>

<p>
  <strong>contact_no:</strong>
  <%= @doctor.contact_no %>
</p>
<p>
  <strong>gender:</strong>
  <%= @doctor.gender %>
</p>

<p><strong>Patients' Information</strong>
<ul>
  <% @patients.each do |patient| %>
    <li><%= patient.name %>  </li>
  <% end %>
</ul>
</p>



  
<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>